apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simpledata-vs
  namespace: demo-circuitbreaker
spec:
  hosts:
  - simpledata.demo-circuitbreaker.svc.cluster.local
  http:
  - route:
    - destination:
        host: simpledata.demo-circuitbreaker.svc.cluster.local
        port:
          number: 8080
        subset: v5
      weight: 100

#  - fault:
# FOR DELAY
#      delay:
#        fixedDelay: 5s
#        percentage:
#          value: 50.0

# FOR ABORT
#      abort:
#        httpStatus: 500
#        percentage:
#          value: 90

# ROUTE FOR FAULT
#    route:
#      - destination:
#          host: simpledata.demo-circuitbreaker.svc.cluster.local
#          port:
#            number: 8080
#          subset: v5
